# This specifies the columns and their order when using the long and the tree
# layout.
# Possible values: permission, user, group, size, size_value, date, name, inode
blocks:
  - permission
  - size
  - name

# What items to display. Do not specify this for the default behavior.
# Possible values: all, almost-all, directory-only
display: almost-all

sorting:
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first
