shell = "zsh"

# create an apply template to defer plugin loading
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# this needs to be loaded before other plugins
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions.hooks]
post = "export ZSH_AUTOSUGGEST_STRATEGY=(history completion)"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath", "defer"]
